[RedisListInput]
address = "127.0.0.1:6379"
key = "logstash"
set_hostname = true

[RstEncoder]

[LogOutput]
message_matcher = "TRUE"
encoder = "RstEncoder"


[ESLogstashV0Encoder]
es_index_from_timestamp = true
type_name = "%{Type}"
timestamp = "%Y-%m-%dT%H:%M:%S.000Z"

[RedisListOutput]
message_matcher = "TRUE"
address = "127.0.0.1:6379"
key = "logstash_staging"
encoder = "ESLogstashV0Encoder"
